version: 2.1

jobs:
  tox:
    docker:
      - image: circleci/python:3.8.1
    steps:
      - checkout
      - run: pip install tox && tox
      - store_artifacts:
          path: htmlcov

workflows:
  python:
    jobs:
      - tox
