name: Auto Assign to Enterprise Plugins Project

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]
env:
  MY_GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    steps:
    - name: Assign NEW issues and NEW pull requests to project enterprise plugins project
      uses: srggrs/assign-one-project-github-action@1.2.1
      if: github.event.action == 'opened'
      with:
        project: 'https://github.com/orgs/grafana/projects/55'
        column_name: Backlog